# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

branches:
  only:
  - master

clone_depth: 5

version: '{build}'

platform:
  - x86

configuration:
  - Release
  - Debug

environment:
  matrix:
    - generator: "Visual Studio 14"
      arch: 32
    #- generator: "MinGW Makefiles"
    #  arch: 32

matrix:
  fast_finish: true

#cache:
#  - C:\projects\fife-dependencies\downloads
#  - C:\projects\fife-dependencies\includes

install:
  - date /T & time /T
  - cmake --version
  # fetch or build dependencies
  - cmake dependencies -G "%generator%" -B../fifengine-dependencies/build
  - cmake --build ../fifengine-dependencies/build --target ALL_BUILD --config %configuration%
  - dir ..\fifengine-dependencies
  - dir ..\fifengine-dependencies\downloads
  - dir ..\fifengine-dependencies\includes /s
  
#before_build:
  # git sh.exe conflicts with MinGW makefiles
  #- if "%generator%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")

build_script:
  - dir
  # create c:\projects\build (out-of-source-tree build)
  - cd.. 
  - mkdir build
  - cd build
  # generate build scripts
  - cmake ..\fifengine -G "%generator%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX="c:/fife/install"

#after_build:
#  -